name: flutter_memory_game
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  lottie: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: VisbyCF
      fonts:
        - asset: assets/fonts/VisbyCF-Heavy.otf
          weight: 900
        - asset: assets/fonts/VisbyCF-HeavyOblique.otf
          weight: 900
          style: italic
        - asset: assets/fonts/VisbyCF-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/VisbyCF-ExtraBoldOblique.otf
          weight: 800
          style: italic
        - asset: assets/fonts/VisbyCF-Bold.otf
          weight: 700
        - asset: assets/fonts/VisbyCF-BoldOblique.otf
          weight: 700
          style: italic
        - asset: assets/fonts/VisbyCF-DemiBold.otf
          weight: 600
        - asset: assets/fonts/VisbyCF-DemiBoldOblique.otf
          weight: 600
          style: italic
        - asset: assets/fonts/VisbyCF-Medium.otf
          weight: 500
        - asset: assets/fonts/VisbyCF-MediumOblique.otf
          weight: 500
          style: italic
        - asset: assets/fonts/VisbyCF-Regular.otf
          weight: 400
        - asset: assets/fonts/VisbyCF-RegularOblique.otf
          weight: 400
          style: italic
        - asset: assets/fonts/VisbyCF-Light.otf
          weight: 300
        - asset: assets/fonts/VisbyCF-LightOblique.otf
          weight: 300
          style: italic
        - asset: assets/fonts/VisbyCF-Thin.otf
          weight: 200
        - asset: assets/fonts/VisbyCF-ThinOblique.otf
          weight: 200
          style: italic


  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/.
    - assets/images/.
    - assets/brain_animation.json
  #   - images/a_dot_ham.jpeg

